# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cole Gibson's Github
email: colergibson@gmail.com
description: 
baseurl: 
url: 
twitter_username: 
github_username:  colergibson

# Build settings
markdown: kramdown
